"""Initial schema - games, pitches, at_bats, teams, players, stats, win_probability

Revision ID: 32ce9cd262c9
Revises: 
Create Date: 2026-03-28 00:49:05.126570
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ce9cd262c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('at_bats',
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('at_bat_index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('inning', sa.Integer(), nullable=False),
    sa.Column('half_inning', sa.String(length=6), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_name', sa.String(length=100), nullable=False),
    sa.Column('batter_id', sa.Integer(), nullable=False),
    sa.Column('batter_name', sa.String(length=100), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rbi', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('is_scoring_play', sa.Boolean(), nullable=False),
    sa.Column('outs_after', sa.Integer(), nullable=False),
    sa.Column('pitch_count', sa.Integer(), nullable=False),
    sa.Column('runner_on_first', sa.Boolean(), nullable=False),
    sa.Column('runner_on_second', sa.Boolean(), nullable=False),
    sa.Column('runner_on_third', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('game_pk', 'at_bat_index')
    )
    op.create_index('ix_at_bats_batter_id', 'at_bats', ['batter_id'], unique=False)
    op.create_index('ix_at_bats_game_pk', 'at_bats', ['game_pk'], unique=False)
    op.create_index('ix_at_bats_pitcher_id', 'at_bats', ['pitcher_id'], unique=False)
    op.create_table('games',
    sa.Column('game_pk', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('game_type', sa.String(length=2), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_name', sa.String(length=100), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('home_team_name', sa.String(length=100), nullable=False),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('home_team_won', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('game_pk')
    )
    op.create_table('pitches',
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('at_bat_index', sa.Integer(), nullable=False),
    sa.Column('pitch_number', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('inning', sa.Integer(), nullable=False),
    sa.Column('half_inning', sa.String(length=6), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_name', sa.String(length=100), nullable=False),
    sa.Column('batter_id', sa.Integer(), nullable=False),
    sa.Column('batter_name', sa.String(length=100), nullable=False),
    sa.Column('pitch_type', sa.String(length=5), nullable=True),
    sa.Column('start_speed', sa.Float(), nullable=True),
    sa.Column('end_speed', sa.Float(), nullable=True),
    sa.Column('spin_rate', sa.Float(), nullable=True),
    sa.Column('spin_direction', sa.Float(), nullable=True),
    sa.Column('break_angle', sa.Float(), nullable=True),
    sa.Column('break_length', sa.Float(), nullable=True),
    sa.Column('pfx_x', sa.Float(), nullable=True),
    sa.Column('pfx_z', sa.Float(), nullable=True),
    sa.Column('plate_x', sa.Float(), nullable=True),
    sa.Column('plate_z', sa.Float(), nullable=True),
    sa.Column('zone', sa.Integer(), nullable=True),
    sa.Column('call_code', sa.String(length=5), nullable=False),
    sa.Column('call_description', sa.String(length=100), nullable=False),
    sa.Column('is_in_play', sa.Boolean(), nullable=False),
    sa.Column('is_strike', sa.Boolean(), nullable=False),
    sa.Column('is_ball', sa.Boolean(), nullable=False),
    sa.Column('launch_speed', sa.Float(), nullable=True),
    sa.Column('launch_angle', sa.Float(), nullable=True),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.Column('trajectory', sa.String(length=50), nullable=True),
    sa.Column('balls', sa.Integer(), nullable=False),
    sa.Column('strikes', sa.Integer(), nullable=False),
    sa.Column('outs', sa.Integer(), nullable=False),
    sa.Column('runner_on_first', sa.Boolean(), nullable=False),
    sa.Column('runner_on_second', sa.Boolean(), nullable=False),
    sa.Column('runner_on_third', sa.Boolean(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('game_pk', 'at_bat_index', 'pitch_number'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_pitches_batter_ts', 'pitches', ['batter_id', 'timestamp'], unique=False)
    op.create_index('ix_pitches_game_pk', 'pitches', ['game_pk'], unique=False)
    op.create_index('ix_pitches_pitcher_ts', 'pitches', ['pitcher_id', 'timestamp'], unique=False)
    op.create_table('player_stats_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('plate_appearances', sa.Integer(), nullable=False),
    sa.Column('at_bats', sa.Integer(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('doubles', sa.Integer(), nullable=False),
    sa.Column('triples', sa.Integer(), nullable=False),
    sa.Column('home_runs', sa.Integer(), nullable=False),
    sa.Column('rbi', sa.Integer(), nullable=False),
    sa.Column('walks', sa.Integer(), nullable=False),
    sa.Column('strikeouts', sa.Integer(), nullable=False),
    sa.Column('innings_pitched', sa.Float(), nullable=False),
    sa.Column('pitches_thrown', sa.Integer(), nullable=False),
    sa.Column('earned_runs', sa.Integer(), nullable=False),
    sa.Column('strikeouts_pitching', sa.Integer(), nullable=False),
    sa.Column('walks_pitching', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_player_stats_daily_player_date', 'player_stats_daily', ['player_id', 'stat_date'], unique=False)
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('primary_position', sa.String(length=5), nullable=False),
    sa.Column('bat_side', sa.String(length=1), nullable=True),
    sa.Column('pitch_hand', sa.String(length=1), nullable=True),
    sa.Column('current_team_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=5), nullable=False),
    sa.Column('league', sa.String(length=20), nullable=False),
    sa.Column('division', sa.String(length=20), nullable=False),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('win_probability_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('inning', sa.Integer(), nullable=False),
    sa.Column('half_inning', sa.String(length=6), nullable=False),
    sa.Column('outs', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('runner_on_first', sa.Boolean(), nullable=False),
    sa.Column('runner_on_second', sa.Boolean(), nullable=False),
    sa.Column('runner_on_third', sa.Boolean(), nullable=False),
    sa.Column('home_win_probability', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_winprob_game_pk', 'win_probability_log', ['game_pk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_winprob_game_pk', table_name='win_probability_log')
    op.drop_table('win_probability_log')
    op.drop_table('teams')
    op.drop_table('players')
    op.drop_index('ix_player_stats_daily_player_date', table_name='player_stats_daily')
    op.drop_table('player_stats_daily')
    op.drop_index('ix_pitches_pitcher_ts', table_name='pitches')
    op.drop_index('ix_pitches_game_pk', table_name='pitches')
    op.drop_index('ix_pitches_batter_ts', table_name='pitches')
    op.drop_table('pitches')
    op.drop_table('games')
    op.drop_index('ix_at_bats_pitcher_id', table_name='at_bats')
    op.drop_index('ix_at_bats_game_pk', table_name='at_bats')
    op.drop_index('ix_at_bats_batter_id', table_name='at_bats')
    op.drop_table('at_bats')
    # ### end Alembic commands ###
