"""Widen team column lengths

Revision ID: 62b88e2adf54
Revises: 32ce9cd262c9
Create Date: 2026-03-28 00:58:36.609295
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b88e2adf54'
down_revision: Union[str, None] = '32ce9cd262c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'abbreviation',
               existing_type=sa.VARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('teams', 'league',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('teams', 'division',
               existing_type=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'division',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('teams', 'league',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('teams', 'abbreviation',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    # ### end Alembic commands ###
