"""add venues and game_weather, venue_id and first_pitch on games

Revision ID: 6a019cacbc01
Revises: 62b88e2adf54
Create Date: 2026-05-07 20:18:19.951223
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a019cacbc01'
down_revision: Union[str, None] = '62b88e2adf54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_weather',
    sa.Column('game_pk', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('observation_time_utc', sa.DateTime(), nullable=False),
    sa.Column('is_indoor', sa.Boolean(), nullable=False),
    sa.Column('temperature_f', sa.Float(), nullable=True),
    sa.Column('feels_like_f', sa.Float(), nullable=True),
    sa.Column('relative_humidity_pct', sa.Float(), nullable=True),
    sa.Column('precipitation_in', sa.Float(), nullable=True),
    sa.Column('wind_speed_mph', sa.Float(), nullable=True),
    sa.Column('wind_gust_mph', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=True),
    sa.Column('pressure_hpa', sa.Float(), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('game_pk')
    )
    op.create_table('venues',
    sa.Column('venue_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('elevation_ft', sa.Float(), nullable=True),
    sa.Column('azimuth_angle', sa.Float(), nullable=True),
    sa.Column('roof_type', sa.String(length=20), nullable=True),
    sa.Column('turf_type', sa.String(length=30), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('venue_id')
    )
    op.add_column('games', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('first_pitch_time_utc', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'first_pitch_time_utc')
    op.drop_column('games', 'venue_id')
    op.drop_table('venues')
    op.drop_table('game_weather')
    # ### end Alembic commands ###
