"""add mlb weather condition fields

Revision ID: 6b09ea1fd844
Revises: 6a019cacbc01
Create Date: 2026-05-07 20:47:01.778393
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b09ea1fd844'
down_revision: Union[str, None] = '6a019cacbc01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_weather', sa.Column('mlb_condition', sa.String(length=50), nullable=True))
    op.add_column('game_weather', sa.Column('mlb_temp_f', sa.Float(), nullable=True))
    op.add_column('game_weather', sa.Column('mlb_wind_text', sa.String(length=50), nullable=True))
    op.add_column('game_weather', sa.Column('roof_closed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_weather', 'roof_closed')
    op.drop_column('game_weather', 'mlb_wind_text')
    op.drop_column('game_weather', 'mlb_temp_f')
    op.drop_column('game_weather', 'mlb_condition')
    # ### end Alembic commands ###
